name: Deploy to Registry

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.12
      - name: Install Pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Unit testing via Pytest
        run: pytest . -v --disable-warnings
  push-to-registry:
    needs: unit-test
    steps:
      - uses: actions/checkout@v3
      - name: Build & Push the image
        run: |
          docker login --username yasir-khalid --password {{ secrets.GHCR }} ghcr.io
          docker build . -t ghcr.io/yasir-khalid/shuttlebot:latest
          docker push ghcr.io/yasir-khalid/shuttlebot:latest
